#!/usr/bin/env node
/* eslint-disable no-console */
/**
 * codegraph-ext/augment.cjs
 *
 * Extends the (gitignored, regenerated) codegraph SQLite DB with three overlays:
 *   #4  covers / mocks  edges  (test file -> source file, + mocked exports)
 *   #3  prop nodes + has_prop  edges (React component prop shapes; native graph has none)
 *   #6  annotation nodes + annotates / mirrors / divergent / todo edges (from annotations.json)
 *
 * All injected rows are tagged so re-running is idempotent:
 *   - nodes:  id LIKE 'ext:%'
 *   - edges:  provenance = 'ext'
 *
 * The DB is wiped/regenerated by `codegraph index`, so this MUST be re-run after every
 * index (see `npm run cg:refresh`). Source of truth for #6 is the git-tracked
 * annotations.json, never the DB.
 */
const { execFileSync } = require("child_process");
const { sqliteBin } = require("./sqlite-bin.cjs");
const fs = require("fs");
const path = require("path");
const crypto = require("crypto");

// This file runs as a COPY inside the target repo, so plain require("ts-morph") resolves against
// the target's node_modules — which is the first thing we try, since a repo that already ships
// ts-morph needs nothing extra. Otherwise fall back to the kit's engine, whose location the indexer
// records in project_metadata.engine_dir.
//
// Resolve FROM that directory rather than joining "node_modules/ts-morph" onto it: ts-morph is the
// kit's own dependency, so it sits in the kit root's node_modules for a git clone and in the
// consumer's for `npm i codegraph-mcp` — never inside engine/ itself. Node's upward walk finds both.
function requireTsMorph() {
  const tried = [];
  const attempt = spec => {
    try {
      return require(spec);
    } catch (_) {
      tried.push(spec);
      return null;
    }
  };
  const attemptFrom = dir => {
    try {
      return require(require.resolve("ts-morph", { paths: [dir] }));
    } catch (_) {
      tried.push(`ts-morph from ${dir}`);
      return null;
    }
  };
  let m = attempt("ts-morph");
  if (m) return m;
  try {
    const dbPath = path.join(__dirname, "..", ".codegraph", "codegraph.db");
    const out = execFileSync(sqliteBin(), ["-json", dbPath, "SELECT value FROM project_metadata WHERE key='engine_dir';"], { encoding: "utf8" });
    const engineDir = out.trim() ? JSON.parse(out)[0].value : null;
    if (engineDir) {
      m = attemptFrom(engineDir);
      if (m) return m;
    }
  } catch (_) {
    /* DB absent */
  }
  if (process.env.CODEGRAPH_ENGINE_DIR) {
    m = attemptFrom(process.env.CODEGRAPH_ENGINE_DIR);
    if (m) return m;
  }
  let dir = __dirname;
  for (let i = 0; i < 8; i++) {
    const store = path.join(dir, "node_modules", ".pnpm");
    if (fs.existsSync(store)) {
      const hit = fs.readdirSync(store).find(d => /^ts-morph@/.test(d));
      if (hit) return require(path.join(store, hit, "node_modules", "ts-morph"));
    }
    dir = path.dirname(dir);
  }
  throw new Error(
    `[augment] cannot resolve ts-morph (tried: ${tried.join(", ")}). ` +
      "Run install.sh, or `npm install` in the kit."
  );
}
const { Project } = requireTsMorph();

const APP_ROOT = path.resolve(__dirname, "..");
const DB = path.join(APP_ROOT, ".codegraph", "codegraph.db");
// Source root: `src/` when present (the common layout), else the repo root.
const SRC = fs.existsSync(path.join(APP_ROOT, "src")) ? path.join(APP_ROOT, "src") : APP_ROOT;
const ANNOTATIONS_FILE = path.join(__dirname, "annotations.json");
const NOW = Date.now();

if (!fs.existsSync(DB)) {
  console.error(`[augment] no codegraph DB at ${DB} — run \`codegraph index\` first.`);
  process.exit(1);
}

// ---------- sqlite helpers ----------
function query(q) {
  const out = execFileSync(sqliteBin(), ["-json", DB, q], { encoding: "utf8", maxBuffer: 256 * 1024 * 1024 });
  return out.trim() ? JSON.parse(out) : [];
}
function runScript(statements) {
  const script = "PRAGMA foreign_keys=OFF;\nBEGIN;\n" + statements.join("\n") + "\nCOMMIT;\n";
  execFileSync(sqliteBin(), [DB], { input: script, encoding: "utf8", maxBuffer: 256 * 1024 * 1024 });
}
const esc = s => String(s == null ? "" : s).replace(/'/g, "''");
const toRel = abs => path.relative(APP_ROOT, abs).split(path.sep).join("/");

// ---------- module specifier resolution ----------
function resolveSpecifier(spec, fromFileAbs) {
  let baseAbs;
  if (spec.startsWith("@/")) baseAbs = path.join(SRC, spec.slice(2));
  else if (spec.startsWith(".")) baseAbs = path.resolve(path.dirname(fromFileAbs), spec);
  else return null; // external package
  const cands = [
    baseAbs + ".ts",
    baseAbs + ".tsx",
    baseAbs + ".js",
    baseAbs + ".jsx",
    path.join(baseAbs, "index.ts"),
    path.join(baseAbs, "index.tsx"),
    path.join(baseAbs, "index.js"),
    path.join(baseAbs, "index.jsx"),
    baseAbs,
  ];
  for (const c of cands) {
    try {
      if (fs.statSync(c).isFile()) return toRel(c);
    } catch (_) {
      /* keep probing */
    }
  }
  return null;
}

// ---------- load existing graph state (for stable joins) ----------
const fileNodeIds = new Set(query("SELECT id FROM nodes WHERE kind='file';").map(r => r.id));
const symbolIndex = new Map(); // `${file_path}\u0000${name}` -> id (first match)
for (const r of query(
  "SELECT id, name, file_path FROM nodes WHERE kind IN ('function','method','class','variable','constant');"
)) {
  const key = r.file_path + "\u0000" + r.name;
  if (!symbolIndex.has(key)) symbolIndex.set(key, r.id);
}
const fileId = rel => (fileNodeIds.has("file:" + rel) ? "file:" + rel : null);

// ---------- ts-morph project ----------
const project = new Project({
  skipAddingFilesFromTsConfig: true,
  skipFileDependencyResolution: true,
  compilerOptions: { allowJs: true, jsx: 2 },
});
// Scan exactly the files the indexer walked (respects .codegraph/config.json includes/excludes),
// so tests living outside src/ (e.g. a top-level test/ dir) still produce covers/mocks edges.
for (const r of query("SELECT path FROM files WHERE path LIKE '%.ts' OR path LIKE '%.tsx';")) {
  try {
    project.addSourceFileAtPath(path.join(APP_ROOT, r.path));
  } catch (_) {
    /* file vanished since indexing */
  }
}
const isTest = p => /\.test\.tsx?$/.test(p);
const isSkippable = p => /(__mocks__|__snapshots__)\//.test(p);

// ---------- accumulators ----------
const extNodes = []; // {id, kind, name, qname, file, signature, doc}
const extEdges = []; // {source, target, kind, metadata}
const seenCovers = new Set();

// ===== #4  covers / mocks =====
function extractJestMockExports(callExpr) {
  const args = callExpr.getArguments();
  if (args.length < 2) return { spec: args[0], exports: null };
  const factory = args[1];
  let obj = null;
  const kind = factory.getKindName ? factory.getKindName() : "";
  if (kind === "ArrowFunction" || kind === "FunctionExpression") {
    const body = factory.getBody && factory.getBody();
    if (body) {
      const bk = body.getKindName();
      if (bk === "ParenthesizedExpression") obj = body.getExpression();
      else if (bk === "ObjectLiteralExpression") obj = body;
      else if (bk === "Block") {
        const ret = body.getStatements().find(s => s.getKindName() === "ReturnStatement");
        if (ret) obj = ret.getExpression();
      }
    }
  }
  if (!obj || obj.getKindName() !== "ObjectLiteralExpression") return { exports: [] };
  const names = [];
  for (const prop of obj.getProperties()) {
    const k = prop.getKindName();
    if (
      k === "PropertyAssignment" ||
      k === "ShorthandPropertyAssignment" ||
      k === "MethodDeclaration" ||
      k === "GetAccessor"
    ) {
      const n = prop.getName && prop.getName();
      if (n) names.push(n);
    }
  }
  return { exports: names };
}

for (const sf of project.getSourceFiles()) {
  const abs = sf.getFilePath();
  const rel = toRel(abs);
  if (!isTest(rel)) continue;
  const testNode = fileId(rel);
  if (!testNode) continue;

  // covers: every import that resolves into src/
  for (const imp of sf.getImportDeclarations()) {
    const spec = imp.getModuleSpecifierValue();
    const resolved = resolveSpecifier(spec, abs);
    if (!resolved) continue;
    const target = fileId(resolved);
    if (!target || target === testNode) continue;
    const key = testNode + "->" + target;
    if (seenCovers.has(key)) continue;
    seenCovers.add(key);
    extEdges.push({ source: testNode, target, kind: "covers", metadata: JSON.stringify({ via: spec }) });
  }

  // mocks: jest.mock("<spec>", factory)
  sf.forEachDescendant(node => {
    if (node.getKindName() !== "CallExpression") return;
    const expr = node.getExpression();
    if (!expr || expr.getText() !== "jest.mock") return;
    const args = node.getArguments();
    if (!args.length || args[0].getKindName() !== "StringLiteral") return;
    const spec = args[0].getLiteralText();
    const resolved = resolveSpecifier(spec, abs);
    if (!resolved) return;
    const target = fileId(resolved);
    if (!target) return;
    const { exports } = extractJestMockExports(node);
    extEdges.push({
      source: testNode,
      target,
      kind: "mocks",
      metadata: JSON.stringify({ specifier: spec, exports: exports || [] }),
    });
  });
}

// ===== #3  prop nodes + has_prop =====
for (const sf of project.getSourceFiles()) {
  const abs = sf.getFilePath();
  const rel = toRel(abs);
  if (isTest(rel) || isSkippable(rel)) continue;
  if (!fileId(rel)) continue;

  const propBearers = [
    ...sf.getInterfaces().map(i => ({ name: i.getName(), members: i.getProperties() })),
    ...sf
      .getTypeAliases()
      .filter(t => t.getTypeNode() && t.getTypeNode().getKindName() === "TypeLiteral")
      .map(t => ({ name: t.getName(), members: t.getTypeNode().getProperties() })),
  ].filter(b => b.name && /Props$/.test(b.name));

  for (const bearer of propBearers) {
    const compName = bearer.name.replace(/Props$/, "");
    const compId = symbolIndex.get(rel + "\u0000" + compName) || fileId(rel);
    for (const m of bearer.members) {
      const pname = m.getName && m.getName();
      if (!pname) continue;
      const typeText = (m.getTypeNode && m.getTypeNode() && m.getTypeNode().getText()) || "";
      const optional = m.hasQuestionToken && m.hasQuestionToken();
      const doc =
        (m.getJsDocs &&
          m
            .getJsDocs()
            .map(d => (d.getComment && d.getComment()) || "")
            .filter(Boolean)
            .join(" ")) ||
        "";
      const propId = `ext:prop:${rel}#${bearer.name}.${pname}`;
      extNodes.push({
        id: propId,
        kind: "prop",
        name: pname,
        qname: `${bearer.name}.${pname}`,
        file: rel,
        signature: (optional ? "?: " : ": ") + typeText,
        doc,
      });
      extEdges.push({
        source: compId,
        target: propId,
        kind: "has_prop",
        metadata: JSON.stringify({ optional: !!optional, type: typeText, component: compName }),
      });
    }
  }
}

// ===== #3b  JSDoc backfill: ext:doc nodes + documents edges =====
// Native nodes carry signatures but almost no docstrings (20/916). Capture the JSDoc
// summary of documented functions/components/hooks so `cg:ask docs <name>` can surface
// intent without opening the file. The doc node links to the symbol via a `documents` edge.
function jsDocSummary(node) {
  const docs = (node.getJsDocs && node.getJsDocs()) || [];
  if (!docs.length) return "";
  const parts = docs
    .map(d => (d.getComment && d.getComment()) || "")
    .filter(Boolean)
    .map(c => (Array.isArray(c) ? c.map(x => (x.getText ? x.getText() : String(x))).join("") : String(c)));
  return parts.join(" ").replace(/\s+/g, " ").trim();
}
for (const sf of project.getSourceFiles()) {
  const abs = sf.getFilePath();
  const rel = toRel(abs);
  if (isTest(rel) || isSkippable(rel)) continue;
  if (!fileId(rel)) continue;

  const documented = [];
  for (const fn of sf.getFunctions()) {
    const name = fn.getName && fn.getName();
    if (name) documented.push({ name, summary: jsDocSummary(fn) });
  }
  for (const vs of sf.getVariableStatements()) {
    const summary = jsDocSummary(vs); // JSDoc sits on the statement, not the declaration
    if (!summary) continue;
    for (const decl of vs.getDeclarations()) {
      const init = decl.getInitializer && decl.getInitializer();
      const k = init && init.getKindName && init.getKindName();
      if (k === "ArrowFunction" || k === "FunctionExpression")
        documented.push({ name: decl.getName(), summary });
    }
  }

  for (const d of documented) {
    if (!d.summary) continue;
    const symId = symbolIndex.get(rel + "\u0000" + d.name);
    if (!symId) continue; // only attach to symbols codegraph actually indexed
    const docId = `ext:doc:${rel}#${d.name}`;
    extNodes.push({
      id: docId,
      kind: "doc",
      name: d.name,
      qname: `${d.name}@${rel}`,
      file: rel,
      signature: "",
      doc: d.summary,
    });
    extEdges.push({
      source: docId,
      target: symId,
      kind: "documents",
      metadata: JSON.stringify({ symbol: d.name }),
    });
  }
}

// ===== #6  annotations -> nodes + edges =====
const ann = JSON.parse(fs.readFileSync(ANNOTATIONS_FILE, "utf8"));
function addAnnotationNode(kind, slug, title, body, files) {
  const id = `ext:annotation:${kind}:${slug}`;
  extNodes.push({
    id,
    kind: "annotation",
    name: slug,
    qname: `${kind}/${slug}`,
    file: "",
    signature: title,
    doc: `${title}\n${body}`,
  });
  for (const f of files || []) {
    const t = fileId(f);
    if (t) extEdges.push({ source: id, target: t, kind: "annotates", metadata: JSON.stringify({ kind }) });
  }
}
for (const c of ann.conventions || []) addAnnotationNode("convention", c.slug, c.title, c.body, c.files);
for (const d of ann.decisions || []) addAnnotationNode("decision", d.slug, d.title, d.body, d.files);
for (const d of ann.dedupe || []) {
  const a = fileId(d.a),
    b = fileId(d.b);
  if (a && b) {
    extEdges.push({
      source: a,
      target: b,
      kind: d.kind, // mirrors | divergent | todo
      metadata: JSON.stringify({ symbol: d.symbol, status: d.status, rationale: d.rationale }),
    });
  }
}

// ---------- emit idempotent SQL ----------
const stmts = ["DELETE FROM edges WHERE provenance='ext';", "DELETE FROM nodes WHERE id LIKE 'ext:%';"];
for (const n of extNodes) {
  stmts.push(
    `INSERT INTO nodes (id,kind,name,qualified_name,file_path,language,start_line,end_line,start_column,end_column,docstring,signature,is_exported,updated_at) ` +
      `VALUES ('${esc(n.id)}','${esc(n.kind)}','${esc(n.name)}','${esc(n.qname)}','${esc(n.file)}','ext',0,0,0,0,'${esc(n.doc)}','${esc(n.signature)}',0,${NOW});`
  );
}
for (const e of extEdges) {
  stmts.push(
    `INSERT INTO edges (source,target,kind,metadata,provenance) ` +
      `VALUES ('${esc(e.source)}','${esc(e.target)}','${esc(e.kind)}','${esc(e.metadata)}','ext');`
  );
}
// ---------- self-heal fingerprint (lets query.cjs detect a wiped/stale overlay) ----------
const annHash = crypto.createHash("md5").update(fs.readFileSync(ANNOTATIONS_FILE)).digest("hex");
const meta = {
  "ext:edge_count": String(extEdges.length),
  "ext:node_count": String(extNodes.length),
  "ext:annotations_hash": annHash,
  "ext:augmented_at": String(NOW),
};
for (const [k, v] of Object.entries(meta)) {
  stmts.push(
    `INSERT OR REPLACE INTO project_metadata (key,value,updated_at) VALUES ('${esc(k)}','${esc(v)}',${NOW});`
  );
}
runScript(stmts);

// ---------- summary ----------
const byKind = (arr, k) => arr.filter(x => x.kind === k).length;
console.log("[augment] done:");
console.log(`  covers   edges: ${byKind(extEdges, "covers")}`);
console.log(`  mocks    edges: ${byKind(extEdges, "mocks")}`);
console.log(
  `  prop     nodes: ${byKind(extNodes, "prop")}   has_prop edges: ${byKind(extEdges, "has_prop")}`
);
console.log(
  `  doc      nodes: ${byKind(extNodes, "doc")}   documents edges: ${byKind(extEdges, "documents")}`
);
console.log(
  `  annotation nodes: ${byKind(extNodes, "annotation")}   annotates edges: ${byKind(extEdges, "annotates")}`
);
console.log(
  `  dedupe edges: mirrors=${byKind(extEdges, "mirrors")} divergent=${byKind(extEdges, "divergent")} todo=${byKind(extEdges, "todo")}`
);
